# frozen_string_literal: true

require "abstract_unit"
require "tmpdir"

class ResolverPublicApiTest < ActiveSupport::TestCase
  class BasicResolver < ActionView::Resolver
    attr_reader :calls

    def initialize
      @calls = []
    end

    private
      def find_templates(name, prefix, partial, details, locals = [])
        @calls << [name, prefix, partial, details, locals]
        [:template]
      end
  end

  test "base resolver find_all normalizes to find_templates and clear_cache is a no op" do
    resolver = BasicResolver.new

    assert_equal [:template], resolver.find_all("show", "posts", true, { formats: [:html] }, nil, [:post])
    assert_equal [["show", "posts", true, { formats: [:html] }, [:post]]], resolver.calls
    assert_nil resolver.clear_cache
  end

  test "file system resolver rejects resolver instances as paths" do
    resolver = ActionView::FileSystemResolver.new(Dir.tmpdir)

    error = assert_raises(ArgumentError) { ActionView::FileSystemResolver.new(resolver) }

    assert_equal "path already is a Resolver class", error.message
  end

  test "file system resolver exposes expanded path identity and equality" do
    Dir.mktmpdir do |dir|
      same = ActionView::FileSystemResolver.new(dir)
      same_again = ActionView::FileSystemResolver.new(File.join(dir, "."))
      other = ActionView::FileSystemResolver.new(Dir.tmpdir)

      assert_equal File.expand_path(dir), same.to_s
      assert same.eql?(same_again)
      assert_equal same, same_again
      assert_not same.eql?(other)
      assert_not same.eql?(Object.new)
    end
  end

  test "file system resolver clear_cache resets path parser and cached templates" do
    Dir.mktmpdir do |dir|
      File.write(File.join(dir, "hello.html.erb"), "Hello")
      resolver = ActionView::FileSystemResolver.new(dir)

      details = { locale: [nil], formats: [:html], variants: [nil], handlers: [:erb] }

      assert_not_empty resolver.find_all("hello", "", false, details)
      assert_nil resolver.clear_cache
      assert_not_empty resolver.find_all("hello", "", false, details)
    end
  end

  test "path parser parses prefix partial locale format variant and handler" do
    parsed = ActionView::Resolver::PathParser.new.parse("admin/users/_card.en.html+phone.erb")

    assert_equal "admin/users/_card", parsed.path.virtual
    assert parsed.path.partial?
    assert_equal :en, parsed.details.locale
    assert_equal :html, parsed.details.format
    assert_equal :phone, parsed.details.variant
    assert_equal :erb, parsed.details.handler
  end

  test "fixture resolver exposes data and string representation" do
    data = { "admin/index.html.erb" => "Admin", "users/show.html.erb" => "User" }
    resolver = ActionView::FixtureResolver.new(data)

    assert_same data, resolver.data
    assert_equal "admin/index.html.erb, users/show.html.erb", resolver.to_s
    assert_empty resolver.find_all("missing", "admin", false, locale: [], formats: [:html], variants: [], handlers: [:erb])
  end

  test "null resolver returns a generated raw template" do
    template = ActionView::NullResolver.new.find_all("show", "admin", true, {}, nil, [:user]).first

    assert_equal "admin/_show", template.virtual_path
    assert_equal "Template generated by Null Resolver", template.source
  end
end

class UnboundTemplatePublicApiTest < ActiveSupport::TestCase
  test "bind locals normalizes local names and reuses built templates" do
    details = ActionView::TemplateDetails.new(nil, :erb, :html, nil)
    unbound = ActionView::UnboundTemplate.new("Hello", "hello.html.erb", details:, virtual_path: "hello")

    first = unbound.bind_locals(["name", :title])
    second = unbound.bind_locals([:title, "name"])

    assert_same first, second
    assert_equal "hello", first.virtual_path
    assert_equal ["name", "title"], first.locals
  end

  test "bind locals collapses cache for strict locals templates" do
    details = ActionView::TemplateDetails.new(nil, :erb, :html, nil)
    unbound = ActionView::UnboundTemplate.new("<%# locals: () %>Hello", "strict.html.erb", details:, virtual_path: "strict")

    first = unbound.bind_locals([])
    second = unbound.bind_locals([:anything])

    assert_predicate first, :strict_locals?
    assert_same first, second
  end
end
